################################# Default configuration ###################
# language
DefaultContentLanguage = "ja"
# provide your domain here
baseURL = "https://gallant-bohr-faa6a7.netlify.app/"
# theme
theme = "dot-mysite"
# site title
title = ""
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/nanjakorewa"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/Y-kyoto/UsefulLinks"

################################ Japanese Language ######################
[Languages.ja]
languageName = "ja"
languageCode = "Ja-jp"
weight = 1
copyright = ""

# banner
[Languages.ja.params.banner]
title = ""
subtitle = ""
placeholder = "テキストを入力してください。"

# call to action
[Languages.ja.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.ja.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################## japanese navigation #################
[[Languages.ja.menu.main]]
name = "Home"
url = "/"
weight = 1

# Dropdown menu
# [[Languages.ja.menu.main]]
# weight = 4
# name = "docs"
# hasChildren = true
# 
#   [[Languages.ja.menu.main]]
#   parent = "docs"
#   name = "Installation"
#   url = "installation"
#   weight = 1
# 
#   [[Languages.ja.menu.main]]
#   parent = "docs"
#   name = "Billing and Pricing"
#   url = "billing-pricing"
#   weight = 2
# 
#   [[Languages.ja.menu.main]]
#   parent = "docs"
#   name = "Features"
#   url = "features"
#   weight = 3
